services:
  influxdb2:
    image: influxdb:2.7
    container_name: influxdb2
    network_mode: "host"
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_TOKEN=${INFLUXDB_INIT_ADMIN_TOKEN}
    #restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    network_mode: "host"
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana-dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_INIT_ADMIN_TOKEN}
      - TZ=America/Bogota
    #restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:latest
    network_mode: "host"
    container_name: mosquitto
    environment:
      - TZ=America/Bogota
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    #restart: unless-stopped

  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=America/Bogota
    network_mode: "host"
    volumes:
      - ./node-red:/data
      - ./tiquetes_pdf:/data/tiquetes_pdf
    #restart: unless-stopped
